#v1.12
#docker build --rm=true -t xxnet-f23:1.0 . -f Dckerfile-xxnet
#docker run --name myxxnet -d --cpuset-cpus=0,1 --cpu-shares=2 -m 128m --cap-drop ALL -u developer f23-xxnet:1.2
#docker load -i ./xxnet-f23.tar 

FROM fedora:1.0
#ADD ./*repo /etc/yum.repos.d/
ADD ./XX-Net-master /home/developer/XX-Net
RUN dnf -y install pyOpenSSL && dnf clean all 
# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer/XX-Net && \
    echo "developer:x:${uid}:${gid}:developer:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R /home/developer

EXPOSE 8084 8085 8086 8087 8888

USER developer
ENV HOME /home/developer

CMD /home/developer/XX-Net/start

