#v1.12
#docker build --rm=true -t xxnet:1.0 . -f Dckerfile-xxnet
#docker network create -d bridge --subnet 172.21.0.0/16 mynetwork
#docker run --name myxxnet -d --network=mynetwork --ip=172.21.0.2 --cpuset-cpus=0,1 --cpu-shares=2 -m 128m --cap-drop ALL -u developer xxnet:1.0
#for ipv6: docker run --name myxxnet -d --network=xxnetwork --ip=172.21.0.2  --cpuset-cpus=0,1 --cpu-shares=2 -m 128m --device=/dev/net/tun:/dev/net/tun  --cap-drop all --cap-add chown --cap-add kill --cap-add  setuid --cap-add  setgid --cap-add net_admin --cap-add net_raw  -u root xxnet:1.0 
#docker load -i ./xxnet-f23.tar 
 
FROM fedora:29
ARG Myappid=
#ADD ./*repo /etc/yum.repos.d/
#ADD ./XX-Net-master /home/developer/XX-Net
RUN dnf -y install dnf-plugins-core && \
    dnf -y config-manager --add-repo=http://repo.fdzh.org/FZUG/FZUG.repo && \
    dnf -y install xx-net miredo iproute&& dnf clean all && \
    export uid=1000 gid=1000 && \
    mkdir -p /home/developer/.xx-net/gae_proxy/ && \
    mkdir -p /home/developer/.xx-net/launcher/ && \
    mkdir -p /home/developer/.xx-net/x_tunnel/ && \
    echo "developer:x:${uid}:${gid}:developer:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "{" >/home/developer/.xx-net/data/gae_proxy/config.json && \
    echo " \"GAE_APPIDS\":[$Myappid]," >>/home/developer/.xx-net/data/gae_proxy/config.json && \
    echo " \"listen_ip\":\"0.0.0.0\"" >>/home/developer/.xx-net/data/gae_proxy/config.json && \
    echo "}" >>/home/developer/.xx-net/data/gae_proxy/config.json && \
    echo "modules:" >/home/developer/.xx-net/launcher/config.yaml && \
    echo "    launcher: {allow_remote_connect: 1, control_port: 8085, popup_webui: 0, proxy: pac,show_systray: 0}" >>/home/developer/.xx-net/launcher/config.yaml && \
    echo "{\"socks_port\": 1080, \"socks_host\": \"0.0.0.0\"}" >>/home/developer/.xx-net/x_tunnel/client.json && \    
    chown ${uid}:${gid} -R /home/developer
     
EXPOSE 8084 8085 8086 8087 8888

USER root
ENV HOME /home/developer

CMD sh -c 'miredo & runuser -l developer  -c "xx-net"'

