#v1.2
#docker run -it  --name firefox -e PULSE_SERVER=10.0.2.15:4713  -u developer firefox:1.2
#http://containerIP:6080

FROM myf23:1.0
#ADD ./*repo /etc/yum.repos.d/


RUN echo "******install chinese fonts******" && \
    dnf -y install adobe-source-han-sans-cn-fonts && \
    
    echo "******install Xvfb fluxbox x11vnc******" && \
    dnf -y install x11vnc xorg-x11-server-Xvfb xorg-x11-utils xorg-x11-xauth fluxbox numpy novnc procps-ng supervisor && \
    
    echo "******install gstream pulseaudio******" && \
    dnf -y install alsa-plugins-pulseaudio  gstreamer1-plugins-base gstreamer1-plugins-good pulseaudio && \
    
    echo "******install flash-plugin******" && \
    dnf -y install http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm && \
    dnf -y --nogpgcheck install flash-plugin && \
        
    dnf -y install which busybox sudo firefox&& \
    dnf -y clean all && \
    #/bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    #/bin/echo -e "ZONE="Asia/Shanghai"\nUTC=false\nRTC=false" > /etc/sysconfig/clock && \
    
    dbus-uuidgen >/var/lib/dbus/machine-id && \
    
    echo "******install busybox******" && \
    busybox --install && \

    echo "******Replace 1000 with your user / group id******" && \
    export uid=1000 gid=1000 && \
    mkdir -p /home/developer/XX-Net && \
    echo "developer:x:${uid}:${gid}:developer:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R /home/developer && \

    sudo -u developer mkdir -p /home/developer/.vnc && \
    sudo -u developer x11vnc -storepasswd 1234 /home/developer/.vnc/passwd && \
    
    mkdir -p /opt/bin/ 
    

#添加 supervisord 的配置文件
COPY supervisord.ini /etc/supervisord.d/supervisord.ini

# 拷贝启动脚本
COPY entry_point4.sh /opt/bin/entry_point4.sh
RUN chmod +x /opt/bin/entry_point4.sh


USER developer
ENV HOME /home/developer

ENV  LANG  en_US.UTF-8

# 屏蔽交互界面
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# 屏幕尺寸和颜色深度
ENV SCREEN_WIDTH 1024
ENV SCREEN_HEIGHT 768
ENV SCREEN_DEPTH 24

# 可以使用任意Unix套接字编号
ENV DISPLAY :99.0

# 暴露VNC的端口  暴露novnc的端口 supervisord:console
EXPOSE 5900     6080             9001


# 设置启动命令
ENV APP_START "firefox"

CMD ["/usr/bin/supervisord"]

