#v1.3
#docker run --rm --name firefox -e PULSE_SERVER=10.0.2.15:4713  -u developer firefox:1.3
#xpra attach tcp:containIP:8900

FROM myf23:1.0
#ADD ./*repo /etc/yum.repos.d/


RUN echo "******install chinese fonts******" && \
    dnf -y install adobe-source-han-sans-cn-fonts && \
    
    echo "******install xvfb xpra xephyr fluxbox******" && \
    dnf -y install xpra xorg-x11-server-Xvfb xorg-x11-server-Xephyr xorg-x11-xauth fluxbox && \
    
    echo "******install gstream pulseaudio******" && \
    dnf -y install alsa-plugins-pulseaudio  gstreamer1-plugins-base gstreamer1-plugins-good pulseaudio && \
    
    echo "******install flash-plugin******" && \
    dnf -y install http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm && \
    dnf -y --nogpgcheck install flash-plugin && \
        
    dnf -y install busybox firefox&& \
    dnf -y clean all && \
    #/bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    #/bin/echo -e "ZONE="Asia/Shanghai"\nUTC=false\nRTC=false" > /etc/sysconfig/clock && \
    
    dbus-uuidgen >/var/lib/dbus/machine-id && \
    
    echo "******install busybox******" && \
    busybox --install && \

    echo "******Replace 1000 with your user / group id******" && \
    export uid=1000 gid=1000 && \
    mkdir -p /home/developer/XX-Net && \
    echo "developer:x:${uid}:${gid}:developer:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R /home/developer && \
    
    mkdir -p /opt/bin/

# 拷贝启动脚本
COPY entry_point3.sh /opt/bin/entry_point3.sh
RUN chmod +x /opt/bin/entry_point3.sh


USER developer
ENV HOME /home/developer

ENV  LANG  en_US.UTF-8

# 屏蔽交互界面
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

# 屏幕尺寸和颜色深度
ENV SCREEN_WIDTH 1024
ENV SCREEN_HEIGHT 768
ENV SCREEN_DEPTH 24

# 可以使用任意Unix套接字编号
ENV DISPLAY :100

# 暴露xpra的端口
EXPOSE 8900

# 设置启动命令
ENV APP_START "firefox"

CMD ["/opt/bin/entry_point3.sh"]

